AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Location Detection AI - Job Management API with Infrastructure

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # DynamoDB Tables
  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-jobs'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expires_at
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: JobStatusStorage

  PreviewCacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${Environment}-preview-cache'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: blueprint_hash
          AttributeType: S
      KeySchema:
        - AttributeName: blueprint_hash
          KeyType: HASH
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: expires_at
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: PreviewCache

  # S3 Buckets
  BlueprintsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'location-detection-${Environment}-blueprints-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: BlueprintStorage

  CacheBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'location-detection-${Environment}-cache-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldFiles
            Status: Enabled
            ExpirationInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: ProcessingCache

  # API Gateway v2 (HTTP API)
  LocationDetectionApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: Location Detection AI REST API
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300

  # Lambda Function for REST API
  ApiRestHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-api-rest-handler'
      CodeUri: src/
      Handler: api.rest_api.handler
      Events:
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref LocationDetectionApi
            Path: /health
            Method: GET
        CreateJob:
          Type: HttpApi
          Properties:
            ApiId: !Ref LocationDetectionApi
            Path: /api/v1/jobs
            Method: POST
        GetJob:
          Type: HttpApi
          Properties:
            ApiId: !Ref LocationDetectionApi
            Path: /api/v1/jobs/{job_id}
            Method: GET
        CancelJob:
          Type: HttpApi
          Properties:
            ApiId: !Ref LocationDetectionApi
            Path: /api/v1/jobs/{job_id}
            Method: DELETE
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PreviewCacheTable
        - S3CrudPolicy:
            BucketName: !Ref BlueprintsBucket
        - S3CrudPolicy:
            BucketName: !Ref CacheBucket
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/location-detection/*'
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:location-detection-*'
      Environment:
        Variables:
          JOBS_TABLE_NAME: !Ref JobsTable
          PREVIEW_CACHE_TABLE_NAME: !Ref PreviewCacheTable
          BLUEPRINTS_BUCKET_NAME: !Ref BlueprintsBucket
          CACHE_BUCKET_NAME: !Ref CacheBucket

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt LocationDetectionApi.ApiEndpoint
  
  HealthEndpoint:
    Description: Health check endpoint URL
    Value: !Sub '${LocationDetectionApi.ApiEndpoint}/health'
  
  JobsTableName:
    Description: DynamoDB table name for jobs
    Value: !Ref JobsTable
    Export:
      Name: !Sub '${Environment}-jobs-table-name'
  
  PreviewCacheTableName:
    Description: DynamoDB table name for preview cache
    Value: !Ref PreviewCacheTable
    Export:
      Name: !Sub '${Environment}-preview-cache-table-name'
  
  BlueprintsBucketName:
    Description: S3 bucket name for blueprint files
    Value: !Ref BlueprintsBucket
    Export:
      Name: !Sub '${Environment}-blueprints-bucket-name'
  
  CacheBucketName:
    Description: S3 bucket name for processing cache
    Value: !Ref CacheBucket
    Export:
      Name: !Sub '${Environment}-cache-bucket-name'

